fun main(){
    println("Student Enrollment number:")
    var a = readLine()?.toIntOrNull()
    println("Student name:")
    var b = readLine()
    println("Student Branch:")
    var c = readLine()
    println("Student Class")
    var d = readLine()
    println("Student Batch:")
    var e = readLine()
    println("Student college Name:")
    var f = readLine()
    println("Student University Name:")
    var g = readLine()
    println("Student age:")
    var h = readLine()?.toInt()

    println("-----Student Details-----")
    println("Enrollment Number:$a")
    println("Name:$b")
    println("Branch:$c")
    println("Class:$d")
    println("Batch:$e")
    println("College Name:$f")
    println("University Name:$g")
    println("Age:$h")
}